const CHANGE_ETHERNET_IP_ADDRESS = 'CHANGE_ETHERNET_IP_ADDRESS';
const CHANGE_ETHERNET_SUBNET_MASK = 'CHANGE_ETHERNET_SUBNET_MASK';
const CHANGE_ETHERNET_DEFAULT_GATE_WAY = 'CHANGE_ETHERNET_DEFAULT_GATE_WAY';
const CHANGE_WIRELESS_DEFAULT_GATE_WAY = 'CHANGE_WIRELESS_DEFAULT_GATE_WAY';
const CHANGE_ETHERNET_PREFERRED_DNS = 'CHANGE_ETHERNET_PREFERRED_DNS';
const CHANGE_WIRELESS_PREFERRED_DNS = 'CHANGE_WIRELESS_PREFERRED_DNS';
const CHANGE_WIRELESS_ALTERNATIVE_DNS = 'CHANGE_WIRELESS_ALTERNATIVE_DNS';
const CHANGE_WIRELESS_IP_ADDRESS = 'CHANGE_WIRELESS_IP_ADDRESS';
const CHANGE_WIRELESS_SUBNET_MASK = 'CHANGE_WIRELESS_SUBNET_MASK';
const CHANGE_ETHERNET_ALTERNATIVE_DNS = 'CHANGE_ETHERNET_ALTERNATIVE_DNS';
const CHANGE_ETHERNET_IP_CHECKBOX = 'CHANGE_ETHERNET_IP_CHECKBOX';
const CHANGE_ETHERNET_DNS_CHECKBOX = 'CHANGE_ETHERNET_DNS_CHECKBOX';
const CHANGE_WIRELESS_IP_CHECKBOX = 'CHANGE_WIRELESS_IP_CHECKBOX';
const CHANGE_WIRELESS_DNS_CHECKBOX = 'CHANGE_WIRELESS_DNS_CHECKBOX';
const CHANGE_WIRELESS_WIFI_CHECKBOX = 'CHANGE_WIRELESS_WIFI_CHECKBOX';
const CHANGE_WIRELESS_SECURITY_CHECKBOX = 'CHANGE_WIRELESS_SECURITY_CHECKBOX';

export {
    CHANGE_ETHERNET_IP_ADDRESS,
    CHANGE_ETHERNET_SUBNET_MASK,
    CHANGE_ETHERNET_DEFAULT_GATE_WAY,
    CHANGE_WIRELESS_DEFAULT_GATE_WAY,
    CHANGE_ETHERNET_PREFERRED_DNS,
    CHANGE_WIRELESS_PREFERRED_DNS,
    CHANGE_WIRELESS_ALTERNATIVE_DNS,
    CHANGE_WIRELESS_IP_ADDRESS,
    CHANGE_WIRELESS_SUBNET_MASK,
    CHANGE_ETHERNET_ALTERNATIVE_DNS,
    CHANGE_ETHERNET_IP_CHECKBOX,
    CHANGE_ETHERNET_DNS_CHECKBOX,
    CHANGE_WIRELESS_IP_CHECKBOX,
    CHANGE_WIRELESS_DNS_CHECKBOX,
    CHANGE_WIRELESS_WIFI_CHECKBOX,
    CHANGE_WIRELESS_SECURITY_CHECKBOX
}