const CHANGE_ETHERNET_IP_ADDRESS = 'CHANGE_ETHERNET_IP_ADDRESS';
const CHANGE_ETHERNET_SUBNET_MASK = 'CHANGE_ETHERNET_SUBNET_MASK';
const CHANGE_ETHERNET_DEFAULT_GATE_WAY = 'CHANGE_ETHERNET_DEFAULT_GATE_WAY';
const CHANGE_WIRELESS_DEFAULT_GATE_WAY = 'CHANGE_WIRELESS_DEFAULT_GATE_WAY';
const CHANGE_ETHERNET_PREFERRED_DNS = 'CHANGE_ETHERNET_PREFERRED_DNS';
const CHANGE_WIRELESS_PREFERRED_DNS = 'CHANGE_WIRELESS_PREFERRED_DNS';
const CHANGE_WIRELESS_ALTERNATIVE_DNS = 'CHANGE_WIRELESS_ALTERNATIVE_DNS';
const CHANGE_WIRELESS_IP_ADDRESS = 'CHANGE_WIRELESS_IP_ADDRESS';
const CHANGE_WIRELESS_SUBNET_MASK = 'CHANGE_WIRELESS_SUBNET_MASK';
const CHANGE_ETHERNET_ALTERNATIVE_DNS = 'CHANGE_ETHERNET_ALTERNATIVE_DNS';
const CHANGE_NETWORK_NAME = 'CHANGE_NETWORK_NAME';
const CHANGE_SECURITY_KEY = 'CHANGE_SECURITY_KEY';
const VALID_ETHERNET_IP_ADDRESS = 'VALID_ETHERNET_IP_ADDRESS';
const VALID_ETHERNET_SUBNET_MASK = 'VALID_ETHERNET_SUBNET_MASK';
const VALID_ETHERNET_PREFERRED_DNS = 'VALID_ETHERNET_PREFERRED_DNS';
const VALID_WIRELESS_IP_ADDRESS = 'VALID_WIRELESS_IP_ADDRESS';
const VALID_WIRELESS_SUBNET_MASK = 'VALID_WIRELESS_SUBNET_MASK';
const VALID_WIRELESS_PREFERRED_DNS = 'VALID_WIRELESS_PREFERRED_DNS';
const VALID_SECURITY_KEY = 'VALID_SECURITY_KEY';
const VALID_NETWORK_NAME = 'VALID_NETWORK_NAME';

export {
    CHANGE_ETHERNET_IP_ADDRESS,
    CHANGE_ETHERNET_SUBNET_MASK,
    CHANGE_ETHERNET_DEFAULT_GATE_WAY,
    CHANGE_WIRELESS_DEFAULT_GATE_WAY,
    CHANGE_ETHERNET_PREFERRED_DNS,
    CHANGE_WIRELESS_PREFERRED_DNS,
    CHANGE_WIRELESS_ALTERNATIVE_DNS,
    CHANGE_WIRELESS_IP_ADDRESS,
    CHANGE_WIRELESS_SUBNET_MASK,
    CHANGE_ETHERNET_ALTERNATIVE_DNS,
    CHANGE_NETWORK_NAME,
    CHANGE_SECURITY_KEY,
    VALID_ETHERNET_IP_ADDRESS,
    VALID_ETHERNET_SUBNET_MASK,
    VALID_ETHERNET_PREFERRED_DNS,
    VALID_WIRELESS_IP_ADDRESS,
    VALID_WIRELESS_SUBNET_MASK,
    VALID_WIRELESS_PREFERRED_DNS,
    VALID_SECURITY_KEY,
    VALID_NETWORK_NAME
}